name: trackerss
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.3
  provider: ^6.1.2
  fl_chart: ^1.0.0
  uuid: ^4.4.0
  # UPDATED: Changed version from ^0.19.0 to ^0.20.2
  intl: ^0.20.2
  table_calendar: ^3.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true

  uses-material-design: true